# yaml-language-server: $schema=https://raw.githubusercontent.com/buildkite/pipeline-schema/main/schema.json
---

agents:
  queue: "android"

steps:
  - label: "Gradle Wrapper Validation"
    command: |
      validate_gradle_wrapper
    plugins: [$CI_TOOLKIT]

  # Wait for Gradle Wrapper to be validated before running any other jobs
  - wait

  - label: "Lint"
    key: "lint"
    plugins: [$CI_TOOLKIT]
    command: |
      ./gradlew lint
    artifact_paths:
      - "**/build/reports/lint-results.*"

  - label: "Publish to S3"
    depends_on:
      - "lint"
    plugins: [$CI_TOOLKIT]
    command: |
      ./gradlew \
          :ucrop:prepareToPublishToS3 $(prepare_to_publish_to_s3_params) \
          :ucrop:publish
